# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 28 Oct 2014 16:50:11 +0000
*               @ALL          1
*               @user         8
