<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Sun, 11 Jan 2015 14:50:40 -0600
 */

$conf['title'] = 'Comunidad de Software y Hardware Libre UESOcc';
$conf['lang'] = 'es';
$conf['template'] = 'monobook';
$conf['tagline'] = '"Solo por diversión" - Linus Torvalds';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['autopasswd'] = 0;
$conf['superuser'] = '@admin';
$conf['plugin']['captcha']['mode'] = 'math';
$conf['plugin']['captcha']['forusers'] = 1;

// end auto-generated content
