<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Wed, 29 Oct 2014 15:57:12 +0000
 */
$conf['title'] = 'Comunidad de software y hardware libre UESOcc';
$conf['lang'] = 'es';
$conf['license'] = 'cc-zero';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
