<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Tue, 28 Oct 2014 16:50:11 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
