<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Sun, 11 Jan 2015 17:21:53 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
